### ISSUE TITLE
issue1 

### ISSUE THREAD

**Issue by lovetony3000** [Lin-Z-J/FaceSystem-SpringBoot#1]
大佬你好，我在复现您的项目的时候没有对应jar包，希望能分享一下

**Comment by Lin-Z-J** [comment]
同学你好，请问你需要哪个jar包



发自我的iPhone


------------------ Original ------------------
From: lovetony3000 ***@***.***&gt;
Date: Sun,May 5,2024 10:00 PM
To: Lin-Z-J/FaceSystem-SpringBoot ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [Lin-Z-J/FaceSystem-SpringBoot] issue1  (Issue #1)





 
大佬你好，我在复现您的项目的时候没有对应jar包，希望能分享一下
